name: zstdless-test

on: push

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - run: less --version
    - name: build newer less
      run: |
        git clone https://github.com/gwsw/less.git
        cd less
        git checkout v643
        make -f Makefile.aut distfiles
        ./configure
        make
        ./less --version
    - name: build zstd
      run: |
        git clone https://github.com/facebook/zstd.git
        cd zstd
        make
    - name: run with system less
      run: cd zstd && tests/cli-tests/run.py --verbose cltools/zstdless.sh
    - name: with newer less
      run: |
        D=$PWD
        cd zstd
        sed -i'' 's/exec less/$D\/less\/less/' programs/zstdless
        tests/cli-tests/run.py --verbose cltools/zstdless.sh