name: zstdless-test

on: push

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - run: less --version
    - name: build newer lesses
      run: |
        git clone https://github.com/gwsw/less.git
        cd less
        git checkout v643
        make -f Makefile.aut distfiles
        ./configure
        make
        mv ./less /tmp/less643

        git checkout v611
        git clean -f.
        rm (cat .gitignore)
        make -f Makefile.aut distfiles
        ./configure
        make
        mv ./less /tmp/less611

        git checkout v610
        git clean -f.
        rm (cat .gitignore)
        make -f Makefile.aut distfiles
        ./configure
        make
        mv ./less /tmp/less610

    - name: build zstd
      run: |
        git clone https://github.com/facebook/zstd.git
        cd zstd
        make
    - name: run with system less
      run: cd zstd && tests/cli-tests/run.py --verbose cltools/zstdless.sh
    - name: prepare with newer lesses
      run: |
        cd zstd
        sed -i'' 's/exec less/exec \/tmp\/less/' programs/zstdless
    - name: run with less v643
      run: |
        rm -f /tmp/less
        ln /tmp/less643 /tmp/less
        cd zstd
        tests/cli-tests/run.py --verbose cltools/zstdless.sh
    - name: run with less v611
      run: |
        rm -f /tmp/less
        ln /tmp/less611 /tmp/less
        cd zstd
        tests/cli-tests/run.py --verbose cltools/zstdless.sh
    - name: run with less v610
      run: |
        rm -f /tmp/less
        ln /tmp/less610 /tmp/less
        cd zstd
        tests/cli-tests/run.py --verbose cltools/zstdless.sh