name: zstdless-test

on: push

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - run: less --version
    - run: sudo apt update && sudo apt install -y strace && sudo apt upgrade -y less
    - run: less --version
    - run: git clone https://github.com/facebook/zstd.git
    - run: cd zstd && make
    - run: cd zstd && tests/cli-tests/run.py --verbose cltools/zstdless.sh
    - name: with strace
      run: |
        cd zstd
        sed -i'' 's/exec less/exec strace --follow-forks less/g' programs/zstdless
        tests/cli-tests/run.py --verbose cltools/zstdless.sh
        sed -i'' 's/exec strace --follow-forks less/exec less/g' programs/zstdless
    - run: cd zstd && make test